name: RPM Test

on:
  workflow_call:
    inputs:
      NAME:
        type: string
        required: true
      DISTROS:
        type: string
        required: true
      TEST_TAG:
        type: string
        required: true

jobs:
  Test-with-DAOS:
    # TODO: investigate how cancelling this can cancel the downstream job
    name: Test RPMs with DAOS
    runs-on: [self-hosted, mockbuilder]
    timeout-minutes: 7200
    strategy:
      fail-fast: false
      matrix:
        # no GHA support on this branch: branch: [master, release/2.4]
        # DO NOT LAND - using PR as master for now
        # branch: [master]
        branch: [bmurrell/run-on-dispatch]
    steps:
      - name: Test RPMs with DAOS
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: daos-stack
          repo: daos
          github_token: ${{ secrets.GHA_WORKFLOW_TRIGGER }}
          comment_downstream_url: ${{ github.event.pull_request.comments_url }}
          workflow_file_name: 'rpm-build-and-test.yml'
          # TODO: or rather I suspect it's a TODO, but I suspect we need to create
          #       a temporary branch here so as not to pollute the landing branch
          #       runs with these tests
          ref: ${{ matrix.branch }}
          wait_interval: 10
          # TODO: rpm-test-version of course needs to either be the latest
          #       version, or better yet, no version and it installs the latest
          #       version
          client_payload: '{"pr-repos":
                              "${{ inputs.NAME }}@PR-${{ github.event.pull_request.number }}:${{ env.GITHUB_RUN_NUMBER }}",
                            "commit-message":
                              "Override commit pragmas",
                            "test-tag":
                              "load_mpi,vm test_core_files,vm ${{ inputs.TEST_TAG }}",
                            "rpm-test-version":
                              "2.5.101",
                            "functional-test-distros":
                              "${{ inputs.DISTROS }}"
                           }'
          propagate_failure: true
      # TODO: investigate how cancelling this can cancel the downstream job
      - name: Cleanup downstream jobs
        if: cancelled()
        run: echo "Cancelling downstream jobs (but how?)"
